server:
  port: 8088  # 端口号
eureka:
  instance:
    hostname: localhost # 主机地址
  client:
    register-with-eureka: false # 注册中心告诉自己不能向自己注册自己，默认为true
#    fetch-registry: false　　　　
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: localhost:8088/eureka/
